"""Credential storage + automated Microsoft Entra (Azure AD) login to refresh
Moodle cookies.txt.

Flow (Waseda → Microsoft 365):
  1. Visit https://<moodle-host>/login/index.php
  2. Follow redirects to Microsoft's login.microsoftonline.com
  3. Fill email → Next → password → Sign in
  4. Dismiss "Stay signed in?" (KMSI) prompt
  5. Land back on Moodle, now with fresh session cookies
  6. Dump all cookies into Netscape cookies.txt

Credentials live in the OS keyring (Windows Credential Manager / macOS Keychain /
Linux Secret Service), not on disk.
"""
from __future__ import annotations

import asyncio
import os
import stat
import sys
import threading
from pathlib import Path
from typing import Callable

import keyring
import keyring.errors

from .config import Config

SERVICE_NAME = "moodle-transcribe"
USERNAME_KEY = "__username__"    # pseudo-entry that stores the current username

Logger = Callable[[str], None]

# Serializes cookie refresh — GUI can spawn one thread, pipeline can trigger
# another concurrently; let them run one at a time instead of racing on the
# same tempfile.
_refresh_lock = threading.Lock()


# --------------------------- credential storage ---------------------------

def _safe_keyring_get(service: str, username: str) -> str | None:
    """keyring.get_password that never raises — returns None on backend errors
    (headless Linux without SecretService, locked Keychain, etc.)."""
    try:
        return keyring.get_password(service, username)
    except keyring.errors.KeyringError:
        return None
    except Exception:
        return None


def _safe_keyring_delete(service: str, username: str) -> None:
    try:
        keyring.delete_password(service, username)
    except keyring.errors.PasswordDeleteError:
        pass
    except keyring.errors.KeyringError:
        pass


def save_credentials(username: str, password: str) -> None:
    """Store creds; if a different username was previously registered, remove
    its stale password entry to avoid leaving old secrets in the keyring."""
    old = _safe_keyring_get(SERVICE_NAME, USERNAME_KEY)
    if old and old != username:
        _safe_keyring_delete(SERVICE_NAME, old)
    keyring.set_password(SERVICE_NAME, USERNAME_KEY, username)
    keyring.set_password(SERVICE_NAME, username, password)


def get_credentials() -> tuple[str, str] | None:
    username = _safe_keyring_get(SERVICE_NAME, USERNAME_KEY)
    if not username:
        return None
    password = _safe_keyring_get(SERVICE_NAME, username)
    if not password:
        return None
    return username, password


def delete_credentials() -> None:
    username = _safe_keyring_get(SERVICE_NAME, USERNAME_KEY)
    if username:
        _safe_keyring_delete(SERVICE_NAME, username)
    _safe_keyring_delete(SERVICE_NAME, USERNAME_KEY)


# --------------------------- cookies.txt writer ---------------------------

def _write_cookies_txt(cookies: list[dict], path: Path) -> None:
    """Write Playwright cookies as Netscape cookies.txt.
    - Unique temp path per call (avoids concurrent-writer clobber).
    - On POSIX, create the temp file directly with mode 0o600 (no window
      during which live session tokens live in a world-readable file).
    - Atomic rename on success.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}.{threading.get_ident()}")
    lines = ["# Netscape HTTP Cookie File", "# Generated by moodle-transcribe", ""]
    for c in cookies:
        domain = c["domain"]
        # Netscape format: column 2 is domain_specified / initial_dot — TRUE if
        # the cookie applies to subdomains (domain starts with '.'), FALSE if
        # host-only. http.cookiejar asserts initial_dot == domain_specified
        # on load, so getting this wrong makes the file unreadable.
        initial_dot = "TRUE" if domain.startswith(".") else "FALSE"
        path_ = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        # Playwright's "expires" is -1 for session cookies; cookies.txt convention is 0
        expires = int(c["expires"]) if c.get("expires", -1) > 0 else 0
        lines.append("\t".join([domain, initial_dot, path_, secure,
                                str(expires), c["name"], c["value"]]))
    body = ("\n".join(lines) + "\n").encode("utf-8")
    try:
        if sys.platform != "win32":
            # O_CREAT|O_EXCL|O_WRONLY with mode 0600 → born with tight perms
            fd = os.open(str(tmp), os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                         stat.S_IRUSR | stat.S_IWUSR)
            try:
                os.write(fd, body)
            finally:
                os.close(fd)
        else:
            tmp.write_bytes(body)
        tmp.replace(path)
    except Exception:
        if tmp.exists():
            tmp.unlink(missing_ok=True)
        raise


# --------------------------- login automation ---------------------------

class LoginError(RuntimeError):
    """Categorized login failure. `reason` is one of:
    - 'sso_picker_missing', 'email_field_missing', 'bad_password',
      '2fa_required', 'kmsi_timeout', 'redirect_timeout', 'network', 'unknown'
    """
    def __init__(self, reason: str, detail: str = "") -> None:
        super().__init__(f"{reason}: {detail}" if detail else reason)
        self.reason = reason
        self.detail = detail


async def _detect_2fa_or_error(page, log: Logger) -> str | None:
    """After clicking the password submit, check which screen we landed on.
    Returns a LoginError.reason string if a known failure is detected."""
    # Wrong password / account error — Microsoft shows an #usernameError or
    # #passwordError div with text.
    for sel, reason in [("#passwordError", "bad_password"),
                        ("#usernameError", "bad_password")]:
        try:
            loc = page.locator(sel)
            if await loc.is_visible(timeout=1500):
                txt = (await loc.inner_text()).strip().splitlines()[0][:120]
                log(f"  ❌ 資格情報エラー: {txt}")
                return reason
        except Exception:
            pass
    # MFA / 2FA challenge pages usually show OTP entry, "approve on your app",
    # authenticator phrases, or specific element IDs.
    for sel in ['input[name="otc"]', "#idTxtBx_SAOTCC_OTC",
                "#idDiv_SAOTCC_Title", 'input[placeholder*="code" i]']:
        try:
            if await page.locator(sel).is_visible(timeout=1500):
                log("  ⚠ 2要素認証が要求されました — 自動ログインは対応していません")
                return "2fa_required"
        except Exception:
            pass
    for kw in ("Approve sign in request", "authenticator app", "Enter code"):
        try:
            if await page.get_by_text(kw).first.is_visible(timeout=1500):
                log(f"  ⚠ 2FA画面検出 ('{kw}')")
                return "2fa_required"
        except Exception:
            pass
    return None


async def _login_flow(cfg: Config, username: str, password: str,
                      headless: bool, log: Logger) -> list[dict]:
    from playwright.async_api import async_playwright, TimeoutError as PWTimeout

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=headless)
        ctx = await browser.new_context()
        try:
            page = await ctx.new_page()
            host = cfg.moodle["host"]
            log(f"  Moodle {host} に接続…")
            try:
                await page.goto(f"https://{host}/login/index.php",
                                wait_until="domcontentloaded", timeout=30000)
            except PWTimeout as e:
                raise LoginError("network", f"Moodleページ読込タイムアウト: {e}")

            # Intermediate SSO picker: "Waseda University Login" / "早稲田..." button.
            sso_clicked = False
            for pattern in ("Waseda University Login", "早稲田", "Waseda", "学生"):
                try:
                    loc = page.get_by_text(pattern).first
                    if await loc.is_visible(timeout=3000):
                        log(f"  SSOピッカーで '{pattern}' をクリック…")
                        await loc.click()
                        sso_clicked = True
                        break
                except Exception:
                    continue

            # Microsoft Entra email step
            try:
                await page.wait_for_selector('input[type="email"]', timeout=15000)
            except PWTimeout:
                detail = "SSOピッカーを通過したがメール入力が出ない" if sso_clicked else "Moodleログインページ構造が変わった可能性"
                raise LoginError("email_field_missing" if sso_clicked else "sso_picker_missing", detail)
            log("  メールアドレス入力…")
            await page.fill('input[type="email"]', username)
            await page.click('input[type="submit"], button[type="submit"], #idSIButton9')

            # Password step
            try:
                await page.wait_for_selector('input[type="password"]', timeout=15000)
            except PWTimeout:
                # Could be "we couldn't find an account with that email"
                raise LoginError("bad_password", "パスワード入力欄が出ない (ID誤りの可能性)")
            log("  パスワード入力…")
            await page.fill('input[type="password"]', password)
            await page.click('input[type="submit"], button[type="submit"], #idSIButton9')

            # After submitting password: may hit error, 2FA, or KMSI/redirect
            reason = await _detect_2fa_or_error(page, log)
            if reason:
                raise LoginError(reason)

            # "Stay signed in?" KMSI prompt — click Yes to persist session
            try:
                await page.wait_for_selector(
                    '#KmsiCheckboxField, input[name="DontShowAgain"], #idSIButton9',
                    timeout=10000)
                log("  Stay signed in → Yes…")
                await page.click('#idSIButton9')
            except PWTimeout:
                log("  KMSI プロンプト無し、スキップ")

            # Wait for redirect back to Moodle
            log("  Moodleへのリダイレクト待機中…")
            try:
                await page.wait_for_url(f"https://{host}/**", timeout=30000)
            except PWTimeout:
                # If we ended on Microsoft's error page, 2FA screen, or never
                # redirected, look again before giving up.
                reason = await _detect_2fa_or_error(page, log)
                raise LoginError(reason or "redirect_timeout",
                                 f"現在URL: {page.url[:100]}")
            # Let Moodle set its own session cookies
            await asyncio.sleep(2)

            # Filter: keep only cookies valid for our Moodle host, so the
            # persisted file doesn't also hold Microsoft/SSO session tokens.
            cookies = await ctx.cookies([f"https://{host}/"])
            return cookies
        finally:
            try:
                await browser.close()
            except Exception:
                pass


_REASON_HINTS = {
    "bad_password":        "ID/パスワード誤り → `moodle-transcribe-cli set-credentials` でやり直し",
    "2fa_required":        "2FA要求 → 拡張で手動エクスポート、または2FAオフを検討",
    "sso_picker_missing":  "Moodleログインページ構造変更の可能性 → 手動エクスポートで当面しのぐ",
    "email_field_missing": "SSO後のMicrosoft画面構造が変わった可能性 → 手動エクスポート",
    "kmsi_timeout":        "ログインは成功したが KMSI 画面で止まった → もう一度試すか手動エクスポート",
    "redirect_timeout":    "Microsoft→Moodleへのリダイレクト失敗 → ネットワーク/VPN確認",
    "network":             "ネットワーク/VPN 接続を確認してください",
    "unknown":             "詳細はログ参照",
}


def refresh_cookies(cfg: Config, log: Logger, *, headless: bool = False) -> bool:
    """Attempt automated cookie refresh using stored credentials.
    Returns True on success, False on failure. Safe to call if no credentials
    are stored — will log and return False cleanly."""
    try:
        creds = get_credentials()
    except Exception as e:
        log(f"  ❌ キーリング参照失敗: {e}")
        log("     Linux headless なら SecretService(gnome-keyring/KWallet) が必要です")
        return False
    if not creds:
        log("  ⚠ 認証情報が未登録 — `moodle-transcribe-cli set-credentials` で登録してください")
        return False
    username, password = creds
    log(f"[Cookie自動更新] user={username[:3]}***")

    with _refresh_lock:
        try:
            cookies = asyncio.run(_login_flow(cfg, username, password, headless, log))
        except LoginError as e:
            hint = _REASON_HINTS.get(e.reason, _REASON_HINTS["unknown"])
            log(f"  ❌ 自動ログイン失敗 [{e.reason}]: {e.detail or ''}")
            log(f"     → {hint}")
            return False
        except Exception as e:
            log(f"  ❌ 自動ログイン失敗 (予期しないエラー): {type(e).__name__}: {e}")
            return False
        try:
            _write_cookies_txt(cookies, cfg.cookies_file)
        except Exception as e:
            log(f"  ❌ cookies.txt の書き出し失敗: {e}")
            return False
    log(f"  ✓ {len(cookies)} cookies を保存: {cfg.cookies_file}")
    return True
