"""Credential storage + automated Microsoft Entra (Azure AD) login to refresh
Moodle cookies.txt.

Flow (Waseda → Microsoft 365):
  1. Visit https://<moodle-host>/login/index.php
  2. Follow redirects to Microsoft's login.microsoftonline.com
  3. Fill email → Next → password → Sign in
  4. Dismiss "Stay signed in?" (KMSI) prompt
  5. Land back on Moodle, now with fresh session cookies
  6. Dump all cookies into Netscape cookies.txt

Credentials live in the OS keyring (Windows Credential Manager / macOS Keychain /
Linux Secret Service), not on disk.
"""
from __future__ import annotations

import asyncio
import time
from pathlib import Path
from typing import Callable

import keyring

from .config import Config

SERVICE_NAME = "moodle-transcribe"
USERNAME_KEY = "__username__"    # pseudo-entry that stores the current username

Logger = Callable[[str], None]


# --------------------------- credential storage ---------------------------

def save_credentials(username: str, password: str) -> None:
    keyring.set_password(SERVICE_NAME, USERNAME_KEY, username)
    keyring.set_password(SERVICE_NAME, username, password)


def get_credentials() -> tuple[str, str] | None:
    username = keyring.get_password(SERVICE_NAME, USERNAME_KEY)
    if not username:
        return None
    password = keyring.get_password(SERVICE_NAME, username)
    if not password:
        return None
    return username, password


def delete_credentials() -> None:
    username = keyring.get_password(SERVICE_NAME, USERNAME_KEY)
    if username:
        try:
            keyring.delete_password(SERVICE_NAME, username)
        except keyring.errors.PasswordDeleteError:
            pass
    try:
        keyring.delete_password(SERVICE_NAME, USERNAME_KEY)
    except keyring.errors.PasswordDeleteError:
        pass


# --------------------------- cookies.txt writer ---------------------------

def _write_cookies_txt(cookies: list[dict], path: Path) -> None:
    """Write Playwright cookies as Netscape cookies.txt."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by moodle-transcribe", ""]
    for c in cookies:
        domain = c["domain"]
        host_only = "FALSE" if domain.startswith(".") else "TRUE"
        path_ = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        # Playwright's "expires" is -1 for session cookies; cookies.txt convention is 0
        expires = int(c["expires"]) if c.get("expires", -1) > 0 else 0
        lines.append("\t".join([domain, host_only, path_, secure,
                                str(expires), c["name"], c["value"]]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------- login automation ---------------------------

async def _login_flow(cfg: Config, username: str, password: str,
                      headless: bool, log: Logger) -> list[dict]:
    from playwright.async_api import async_playwright

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=headless)
        ctx = await browser.new_context()
        page = await ctx.new_page()
        host = cfg.moodle["host"]
        log(f"  Moodle {host} に接続…")
        await page.goto(f"https://{host}/login/index.php", wait_until="domcontentloaded", timeout=30000)

        # Microsoft Entra login page
        # Email step
        try:
            await page.wait_for_selector('input[type="email"]', timeout=15000)
        except Exception as e:
            # Might already be at an intermediate SSO picker — look for anchor text
            raise RuntimeError(f"Microsoftログインページに到達できませんでした: {e}")
        log("  メールアドレス入力…")
        await page.fill('input[type="email"]', username)
        await page.click('input[type="submit"], button[type="submit"], #idSIButton9')

        # Password step
        await page.wait_for_selector('input[type="password"]', timeout=15000)
        log("  パスワード入力…")
        await page.fill('input[type="password"]', password)
        await page.click('input[type="submit"], button[type="submit"], #idSIButton9')

        # "Stay signed in?" KMSI prompt — click Yes to persist session
        try:
            await page.wait_for_selector('#KmsiCheckboxField, input[name="DontShowAgain"], #idSIButton9',
                                          timeout=10000)
            log("  Stay signed in → Yes…")
            await page.click('#idSIButton9')
        except Exception:
            log("  KMSI プロンプト無し、スキップ")

        # Wait for redirect back to Moodle
        log(f"  Moodleへのリダイレクト待機中…")
        await page.wait_for_url(f"https://{host}/**", timeout=30000)
        # Let Moodle set its own session cookies
        await asyncio.sleep(2)

        cookies = await ctx.cookies()
        await browser.close()
        return cookies


def refresh_cookies(cfg: Config, log: Logger, *, headless: bool = False) -> bool:
    """Attempt automated cookie refresh using stored credentials.
    Returns True on success, False on failure. Safe to call if no credentials
    are stored — will just log a warning."""
    creds = get_credentials()
    if not creds:
        log("  ⚠ 認証情報が未登録 — `moodle-transcribe-cli set-credentials` で登録してください")
        return False
    username, password = creds
    log(f"[Cookie自動更新] user={username[:3]}***")
    try:
        cookies = asyncio.run(_login_flow(cfg, username, password, headless, log))
    except Exception as e:
        log(f"  ❌ 自動ログイン失敗: {e}")
        log("     2FA要求やページ構造変更の可能性。GUIの「Cookie更新 (手動)」を試してください")
        return False
    _write_cookies_txt(cookies, cfg.cookies_file)
    log(f"  ✓ {len(cookies)} cookies を保存: {cfg.cookies_file}")
    return True
